# ===================================================================
# Spring Boot configuration for the "heroku" profile.
#
# This configuration overrides the application.yml file.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

eureka:
    instance:
        hostname: motorsports-database.herokuapp.com
        non-secure-port: 80
        prefer-ip-address: false
    client:
        serviceUrl:
            defaultZone: ${JHIPSTER_REGISTRY_URL}/eureka/

spring:
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        maximumPoolSize: 9
        url: ${JDBC_DATABASE_URL}&verifyServerCertificate=false&useSSL=false
        username: ${JDBC_DATABASE_USERNAME}
        password: ${JDBC_DATABASE_PASSWORD}
    data:
        mongodb:
            uri: ${MONGODB_URI}?authMode=scram-sha1
        # elasticsearch:
        #     cluster-name:
        #     cluster-nodes: #${BONSAI_URL}

# Not sure if this needs to be added here
application:
  sendgrid:
      key: ${SENDGRID_API_KEY}